spring:
  application:
    name: execution-service

  datasource:
    url: jdbc:mariadb://localhost:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

server:
  port: ${SERVER_PORT}
